# Generated by Django 5.2.5 on 2025-10-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_aipufamily_family_photo_chakorufamily_family_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipufamily',
            name='birth_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of birth (1 for firstborn, etc.)'),
        ),
        migrations.AddField(
            model_name='chakorufamily',
            name='birth_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of birth (1 for firstborn, etc.)'),
        ),
        migrations.AddField(
            model_name='francisfamily',
            name='birth_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of birth (1 for firstborn, etc.)'),
        ),
        migrations.AddField(
            model_name='kochuvareedfamily',
            name='birth_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of birth (1 for firstborn, etc.)'),
        ),
        migrations.AddField(
            model_name='lonappanfamily',
            name='birth_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of birth (1 for firstborn, etc.)'),
        ),
        migrations.AddField(
            model_name='thomafamily',
            name='birth_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of birth (1 for firstborn, etc.)'),
        ),
        migrations.AddField(
            model_name='varunnyfamily',
            name='birth_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of birth (1 for firstborn, etc.)'),
        ),
    ]
