# Generated by Django 5.2.5 on 2025-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('membership_no', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
