# Generated by Django 5.2.5 on 2025-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_lifemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='year',
            field=models.CharField(blank=True, help_text="Example: '2011 - 2012'", max_length=20),
        ),
    ]
